# Numpy练习题

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.5


In [3]:
z = np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
print('%d bytes'%(z.size * z.itemsize))

200 bytes


In [5]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
print(help(np.info(np.array)))

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (column major

In [7]:
guo_array = np.arange(10,50,1)
guo_array = guo_array[::-1]
guo_array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
#返回不为0的索引
np.nonzero([1,2,3,4,5,0,0,0,1,2,3,4,0,1])

(array([ 0,  1,  2,  3,  4,  8,  9, 10, 11, 13], dtype=int64),)

In [9]:
guo_array = np.random.random((3,3))
guo_array.min()

0.09566770460567542

In [10]:
guo_array.max()

0.9828528918394395

In [11]:
guo_array = np.ones((5,5))
guo_array = np.pad(guo_array, pad_width=1, mode='constant', constant_values = 0)

In [12]:
guo_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
print(help(np.info(np.pad)))

 pad(array, pad_width, mode='constant', **kwargs)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ((before_1, after_1), ... (before_N, after_N)) unique pad widths
    for each axis.
    ((before, after),) yields same before and after pad for each axis.
    (pad,) or int is a shortcut for before = after = pad width for all
    axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
  

In [14]:
guo_array = np.ones((5,5))
guo_array = np.pad(guo_array, pad_width=2, mode='constant', constant_values = 0)
guo_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

In [16]:
guo_array = np.random.random((5,5))
guo_array

array([[0.43050983, 0.24608024, 0.1485726 , 0.56912472, 0.00617702],
       [0.15631379, 0.51161504, 0.20962752, 0.54862823, 0.94196451],
       [0.56038178, 0.76115183, 0.7231529 , 0.22186007, 0.16820374],
       [0.81938866, 0.42316338, 0.35268619, 0.87824752, 0.06844944],
       [0.66712559, 0.64333329, 0.46969165, 0.02496958, 0.18633238]])

In [17]:
_max = guo_array.max()
_min = guo_array.min()

In [18]:
guo_array = (guo_array - _min)/(_max - _min)
guo_array

array([[0.45344997, 0.25636507, 0.15216658, 0.60157643, 0.        ],
       [0.16043896, 0.54012051, 0.21741101, 0.5796735 , 1.        ],
       [0.59223357, 0.80678019, 0.76617382, 0.23048293, 0.17314478],
       [0.86901316, 0.44559941, 0.37028617, 0.93191083, 0.06654547],
       [0.70630199, 0.68087709, 0.4953204 , 0.02008209, 0.19251739]])

In [20]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(z1)
print(z2)
print(np.intersect1d(z1, z2))

[9 2 2 3 8 1 7 9 4 0]
[0 1 5 9 9 9 7 0 5 3]
[0 1 3 7 9]


In [23]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [24]:
yesterday

numpy.datetime64('2024-08-08')

In [25]:
today

numpy.datetime64('2024-08-09')

In [26]:
tomorrow

numpy.datetime64('2024-08-10')

In [28]:
np.arange('2017-10', '2017-11', dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

In [30]:
z = np.random.uniform(0, 10, 10)
np.floor(z) #得到整数部分

array([6., 2., 0., 5., 5., 0., 7., 6., 2., 0.])

In [31]:
z = np.zeros(5)

In [32]:
z

array([0., 0., 0., 0., 0.])

In [33]:
z.flags.writeable = False
z

array([0., 0., 0., 0., 0.])

In [34]:
z = np.zeros((15,15))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [35]:
z = np.arange(100)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [36]:
v = np.random.uniform(0, 100)
v

0.9713163207041631

In [37]:
index = (np.abs(z-v)).argmin()
print(z[index])

1


In [39]:
z = np.arange(10, dtype=np.int32)
print(z.dtype)
z = z.astype(np.float32)
print(z.dtype)

int32
float32


In [40]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):  #numpy中的枚举操作
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [41]:
z = np.random.randint(0, 10, (3,3))
print(z)
print(z[z[:,1].argsort()])

[[4 8 2]
 [6 8 2]
 [3 2 9]]
[[3 2 9]
 [4 8 2]
 [6 8 2]]


In [42]:
z = np.array([1,1,1,2,2,2,3,3,3,4,4,4])
np.bincount(z)

array([0, 3, 3, 3, 3], dtype=int64)

In [43]:
z = np.random.randint(0, 10, (4,4,4,4))
res = z.sum(axis=(-2,-1))
res

array([[56, 64, 71, 58],
       [80, 79, 68, 81],
       [75, 64, 54, 59],
       [82, 59, 71, 83]])

In [47]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
z

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
z[[0,2]] = z[[2,0]]
z       #交换矩阵的两行

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
z = np.random.randint(0,10,50)

In [50]:
print(np.bincount(z).argmax())

2


In [53]:
z = np.arange(10000000)
np.random.shuffle(z)
n = 5
print(z[np.argpartition(-z, n)[:n]])

[9999999 9999998 9999997 9999996 9999995]


In [54]:
z = np.random.randint(0,5,(10,3))
z

array([[2, 3, 1],
       [4, 3, 0],
       [2, 0, 0],
       [2, 2, 0],
       [3, 2, 1],
       [2, 1, 0],
       [0, 1, 2],
       [1, 4, 2],
       [0, 0, 2],
       [0, 1, 2]])

In [55]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
np.all(a==b)

False

In [56]:
np.any(a==b)

True

In [57]:
e = np.all(z[:,1:]== z[:,:-1], axis=1)
print(e)

[False False False False False False False False False False]
