In [1]:
import torch

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [2]:
x[3]

tensor(3)

In [3]:
len(x)

4

In [4]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [5]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [6]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [7]:
B = torch.arange(20).reshape(5,4)
A * B
#Hadamard product

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [8]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [9]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [10]:
A = torch.arange(20).reshape(5,4)
A.sum()/ A.numel()

tensor(9.5000)

In [11]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

In [12]:
#通过广播机制将A除以A_sum
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [13]:
A.cumsum(axis=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

In [14]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [15]:
torch.sum(x * y)

tensor(6.)

In [16]:
A.shape

torch.Size([5, 4])

In [17]:
x.shape

torch.Size([4])

In [18]:
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [20]:
torch.abs(u).sum()

tensor(7.)

In [22]:
torch.norm(torch.ones((4,9)))

tensor(6.)

In [23]:
x = torch.arange(6).reshape(2,3)

torch.sum(x, axis=0)

tensor([3, 5, 7])

In [24]:
torch.sum(x, axis=1)

tensor([ 3, 12])

keepdims=True时

不会把维度去掉

例如:

shape:[2,5,4]

axis = 1

==>

shape:[2,1,4]

In [27]:
a = torch.ones(2,5,4)
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [28]:
a.shape

torch.Size([2, 5, 4])

In [29]:
a.sum(axis=1)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [30]:
a.sum(axis=1).shape

torch.Size([2, 4])

In [31]:
a.sum(axis=1, keepdims=True).shape

torch.Size([2, 1, 4])

In [32]:
a.sum(axis=[0,2])

tensor([8., 8., 8., 8., 8.])

In [33]:
a.sum(axis=[0,2]).shape

torch.Size([5])

张量表示:统计学引出

copy和clone的区别: copy有可能copy内存

行向量称为向量

列向量称为矩阵